config/routes.rb
Rails.application.routes.draw do
  resources :packages do
    post :toggle, on: :member
  end
  resources :couriers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => redirect('/couriers')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
    has_many :packages, dependent: :destroy
    validates :name, :email, presence: true
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier

  scope :completed, -> { where(delivery_status: true) }
  scope :uncompleted, -> { where(delivery_status: false) }

  def toggle_completed!
    toggle!(:delivery_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: [:show, :edit, :update, :destroy]

  # GET /couriers
  # GET /couriers.json
  def index
    @couriers = Courier.all
  end

  # GET /couriers/1
  # GET /couriers/1.json
  def show
    @package = Package.new
  end

  # GET /couriers/new
  def new
    @courier = Courier.new
  end

  # GET /couriers/1/edit
  def edit
  end

  # POST /couriers
  # POST /couriers.json
  def create
    @courier = Courier.new(courier_params)

    respond_to do |format|
      if @courier.save
        format.html { redirect_to @courier, notice: 'Courier was successfully created.' }
        format.json { render :show, status: :created, location: @courier }
      else
        format.html { render :new }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couriers/1
  # PATCH/PUT /couriers/1.json
  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to @courier, notice: 'Courier was successfully updated.' }
        format.json { render :show, status: :ok, location: @courier }
      else
        format.html { render :edit }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couriers/1
  # DELETE /couriers/1.json
  def destroy
    @courier.destroy
    respond_to do |format|
      format.html { redirect_to couriers_url, notice: 'Courier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courier
      @courier = Courier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def courier_params
      params.require(:courier).permit(:name, :email)
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy, :toggle]
 
  # GET /packages
  # GET /packages.json
  def index
    @packages = Package.all
  end

  # GET /packages/1
  # GET /packages/1.json
  def show
    @courier = @package.courier
  end

  # GET /packages/new
  def new
    @package = Package.new
  end

  
  # GET /packages/1/edit
  def edit
    @courier = @package.courier
  end

  # POST /packages
  # POST /packages.json
  def create
    @package = Package.new(package_params)
    @courier = @package.courier

    respond_to do |format|
      if @package.save
        format.html { redirect_to @courier, notice: 'Package was successfully created.' }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package, notice: 'Package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @courier = @package.courier
    @package.destroy
    respond_to do |format|
      format.html { redirect_to @courier, notice: 'Package was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  def toggle
    @package.toggle_completed!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package
      @package = Package.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def package_params
      params.require(:package).permit(:name, :tracking_number, :delivery_status, :courier_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.erb
<%= form_with(model: courier, local: true) do |form| %>
  <% if courier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(courier.errors.count, "error") %> prohibited this courier from being saved:</h2>

      <ul>
        <% courier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/couriers/edit.html.erb
<h1>Editing Courier</h1>

<%= render 'form', courier: @courier %>

<%= link_to 'Show', @courier %> |
<%= link_to 'Back', couriers_path %>

app/views/couriers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Couriers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @couriers.each do |courier| %>
      <tr>
        <td><%= courier.name %></td>
        <td><%= courier.email %></td>
        <td><%= link_to 'Show', courier %></td>
        <td><%= link_to 'Edit', edit_courier_path(courier) %></td>
        <td><%= link_to 'Destroy', courier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Courier', new_courier_path %>

app/views/couriers/new.html.erb
<h1>New Courier</h1>

<%= render 'form', courier: @courier %>

<%= link_to 'Back', couriers_path %>

app/views/couriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @courier.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @courier.email %>
</p>

<%= link_to 'Edit', edit_courier_path(@courier) %> |
<%= link_to 'Back', couriers_path %>

<p>
  <strong>New Package</strong>
  <%= form_with model: @package do |f| %>
			<%= f.hidden_field :courier_id, :value => @courier.id %>
			<%= f.text_field :name, placeholder: "What are we delivering, buddy?", autocomplete: :off, required: true, 
				data: { placeholder: :new_package_input, "courier-id": @courier.id } %>
			<%= f.submit "Add Package", render: courier_path(@courier), remote: true %>		
	<% end %>
</p>

<p>
  <div class="package-list package-list--uncompleted">
		<ul id="packages" style="list-style-type:none" data-placeholder="uncompleted_packages" data-courier-id="<%= @courier.id %>">
			<%= render @courier.packages.uncompleted %>
		</ul>
	</div>
</p>

<p>
	<div class="package-list package-list--completed">
		<ul id="packages-completed" style="list-style-type:none" data-placeholder="completed_packages" data-courier-id="<%= @courier.id %>">
			<%= render @courier.packages.completed %>
		</ul>
	</div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>